# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 768422d44cae12a7b0a4d6c468cf3e6256e37a5da894fae5b38470ead3275cc3d580bdf24863cfcd7d982b64097ea43aa30841fcbff01c90a209bb87c508ac17

test:
  secret_key_base: f0b23c72b5c56120412d3932e3932dc7ecac9204a28ec761ee53b8ecdf887aff4d94aa44ef1177394aec19d6d9299747b330a774c291761d6205e9c94389bdb3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
